version: "3.10"

services:
  postgres:
    image: postgres:15.5
    container_name: win_calc_db
    ports:
      - "5440:5432"
    environment:
      - TZ=${TZ:-Europe/Moscow}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-dev_win_calc_db}
    restart: on-failure
    volumes:
      - "database:/var/lib/postgresql/data"
      - "./server/scripts/init-schemas.sql:/docker-entrypoint-initdb.d/init-schemas.sql"
    networks:
      - win-calc-net

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_container
    ports:
      - "8081:8081"
    env_file:
      - ./server/.env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-dev_win_calc_db}
    depends_on:
      - postgres
    networks:
      - win-calc-net

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_container
    depends_on:
      - server
    networks:
      - win-calc-net

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - client
      - server
    networks:
      - win-calc-net

networks:
  win-calc-net:
    name: win-calc-net
    driver: bridge

volumes:
  database: