version: "3.10"

services:
  postgres:
    image: postgres:15.5
    container_name: win_calc_db
    ports:
      - "5440:5432"
    environment:
      - TZ=${TZ:-Europe/Moscow}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-dev_win_calc_db}
    restart: on-failure
    volumes:
      - "database:/var/lib/postgresql/data"
      - "./scripts/init-schemas.sql:/docker-entrypoint-initdb.d/init-schemas.sql"

networks:
  win-calc-net:
    name: win-calc-net
    driver: bridge

volumes:
  database: