server:
  port: 8081

jwt:
  access:
    secret: VERY_SECRET_PHRASE_OOOF
    duration: 50 # minutes
  refresh:
    secret: VERY_SECRET_PHRASE_FOR_REFRESH_TOKEN_OOOF
    duration: 30 # days

spring:
  application:
    name: window_calculator

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5440}/${POSTGRES_DB:dev_win_calc_db}?currentSchema=win_calc_schema
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver

  flyway:
    schemas: win_calc_schema
    clean-on-validation-error: true
    clean-disabled: false

  docker:
    compose:
      enabled: false

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health

logging:
  level:
    org:
      springframework:
        security:
          web: OFF