import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from './_theme/theme';
import './_styles/variables.css';
import { Roboto } from 'next/font/google';
import { CssBaseline } from '@mui/material';
import AxiosInterceptorProvider from '@/providers/AxiosInterceptorProvider';
import AuthProvider from '@/providers/AuthProvider';
import ErrorSnackbar from '@/components/errors/ErrorSnackbar';
import AnimatedBackground from '@/components/backgrounds/AnimatedBackground';

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata = {
  title: 'Window calculator',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>

      <body className={roboto.variable}>
        <AnimatedBackground />
        <AppRouterCacheProvider options={{ key: 'css' }}>
          <ThemeProvider theme={theme}>
            <AxiosInterceptorProvider>
              <AuthProvider>
                <CssBaseline />
                <ErrorSnackbar />
                {children}
              </AuthProvider>
            </AxiosInterceptorProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
